[package]
name = "sdl3cube"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl3-sys = { version = "0.1.3", features = [ "build-from-source" ] }
glam = "0.29.2"

[build-dependencies]
naga = { version = "23.0.0", features = [ "wgsl-in", "spv-out" ] }

[features]
vulkan = []
dx12 = []
metal = []
